name: flutter_app
description: A secure encrypted photo gallery application.
publish_to: 'none'
version: 2026.8.12

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  encrypt: ^5.0.1
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.8
  image_gallery_saver_plus: ^5.1.1
  shared_preferences: ^2.2.2
  package_info_plus: ^8.0.0
  permission_handler: ^11.0.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
